### ISSUE TITLE
DOI not found

### ISSUE THREAD

**Issue by hexratcc** [InteractiveComputerGraphics/stark_magnetic#1]
The provided DOI in the README doesn't lead anywhere (https://doi.org/10.1111/cgf.15185).

**Comment by BjoernBinaer** [comment]
Thank you for reporting this issue. I've forwarded this to the publisher such that this can be fixed ASAP. In the meantime, feel free to access the publication via our chair's website:

- https://animation.rwth-aachen.de/publication/0590/

Cheers,
Lukas
